import type { Ride } from './types';

export const RIDES: Ride[] = [
  {
    id: '1',
    name: 'Toyota Camry 2021',
    type: 'Standard',
    price: 15000,
    pickup: 'Ikeja',
    destination: 'Lekki',
    owner: {
      name: 'John Adebayo',
      contact: {
        phone: '2348012345678',
        whatsapp: '2348012345678',
        email: 'john.adebayo@example.com',
      },
    },
    image: 'sedan-1',
    isPromoted: true,
  },
  {
    id: '2',
    name: 'Honda CR-V 2022',
    type: 'SUV',
    price: 25000,
    pickup: 'Surulere',
    destination: 'Victoria Island',
    owner: {
      name: 'City Movers Ltd.',
      contact: {
        phone: '2348023456789',
        whatsapp: '2348023456789',
        email: 'contact@citymovers.com',
      },
    },
    image: 'suv-1',
    isPromoted: false,
  },
  {
    id: '3',
    name: 'Mercedes-Benz E-Class',
    type: 'Luxury',
    price: 45000,
    pickup: 'Banana Island',
    destination: 'Ikeja GRA',
    owner: {
      name: 'Prestige Rides',
      contact: {
        phone: '2348034567890',
        whatsapp: '2348034567890',
        email: 'bookings@prestigerides.ng',
      },
    },
    image: 'luxury-1',
    isPromoted: true,
  },
  {
    id: '4',
    name: 'Ford Transit',
    type: 'Shared',
    price: 5000,
    pickup: 'Yaba',
    destination: 'Marina',
    owner: {
      name: 'Go-Together Shuttles',
      contact: {
        phone: '2348045678901',
        whatsapp: '2348045678901',
        email: 'support@gotogether.ng',
      },
    },
    image: 'van-1',
    isPromoted: false,
  },
    {
    id: '5',
    name: 'Lexus ES 350',
    type: 'Standard',
    price: 18000,
    pickup: 'Lekki',
    destination: 'Ikeja',
    owner: {
      name: 'Chioma Nwosu',
      contact: {
        phone: '2348056789012',
        whatsapp: '2348056789012',
        email: 'chioma.n@example.com',
      },
    },
    image: 'sedan-2',
    isPromoted: false,
  },
  {
    id: '6',
    name: 'Toyota Highlander',
    type: 'SUV',
    price: 30000,
    pickup: 'Victoria Island',
    destination: 'Magodo',
    owner: {
      name: 'Safe Journey Ltd.',
      contact: {
        phone: '2348067890123',
        whatsapp: '2348067890123',
        email: 'safe@journey.com',
      },
    },
    image: 'suv-2',
    isPromoted: false,
  },
  {
    id: '7',
    name: 'BMW 5 Series',
    type: 'Luxury',
    price: 50000,
    pickup: 'Ikoyi',
    destination: 'Eko Atlantic',
    owner: {
      name: 'Prestige Rides',
      contact: {
        phone: '2348034567890',
        whatsapp: '2348034567890',
        email: 'bookings@prestigerides.ng',
      },
    },
    image: 'luxury-2',
    isPromoted: false,
  },
  {
    id: '8',
    name: 'Toyota Coaster',
    type: 'Shared',
    price: 7000,
    pickup: 'Ajah',
    destination: 'CMS',
    owner: {
      name: 'Go-Together Shuttles',
      contact: {
        phone: '2348045678901',
        whatsapp: '2348045678901',
        email: 'support@gotogether.ng',
      },
    },
    image: 'shared-1',
    isPromoted: false,
  },
  {
    id: '9',
    name: 'Honda Accord',
    type: 'Standard',
    price: 16000,
    pickup: 'Maryland',
    destination: 'Apapa',
    owner: {
      name: 'Tunde Bello',
      contact: {
        phone: '2348078901234',
        whatsapp: '2348078901234',
        email: 'tunde.b@example.com',
      },
    },
    image: 'sedan-3',
    isPromoted: false,
  },
  {
    id: '10',
    name: 'GAC GS8',
    type: 'SUV',
    price: 32000,
    pickup: 'Gbagada',
    destination: 'Ikoyi',
    owner: {
      name: 'Comfort Drives',
      contact: {
        phone: '2348089012345',
        whatsapp: '2348089012345',
        email: 'info@comfortdrives.com',
      },
    },
    image: 'suv-3',
    isPromoted: true,
  }
];
